# Use an official Node.js runtime as a parent image
FROM node:22-alpine AS base
RUN apk add --no-cache bash
# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY apps/logging-service/package*.json ./

# Copy wait-for-it.sh
COPY scripts/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x ./wait-for-it.sh

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY apps/logging-service ./
COPY libs ./libs


# Expose the port the app runs on
EXPOSE 5002

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3000/health || exit 1

# Define the command to run the app
CMD ["sh", "-c", "/usr/src/scripts/wait-for-it.sh rabbitmq:5672  -- npm run start:${RUN_MODE}"]