services:
  api-gateway:
    build:
      context: ../
      dockerfile: apps/api-gateway/dockerfile
    container_name: api-gateway
    env_file:
      - ../apps/api-gateway/.env.dev
    environment:
      - RUN_MODE=${RUN_MODE:-dev}

    ports:
      - "5000:5000"
      - "9229:9229"
    volumes:
      - ../apps/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
      - ../libs:/usr/src/libs
    networks:
      - service-network
    depends_on:
      - rabbitmq
      - logging-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  auth-service:
    build:
      context: ../
      dockerfile: apps/auth-service/dockerfile
    container_name: auth-service
    env_file:
      - ../apps/auth-service/.env.dev
    environment:
      - RUN_MODE=${RUN_MODE:-dev}

    ports:
      - "5001:5001"
      - "9230:9230"

    volumes:
      - ../apps/auth-service:/usr/src/app
      - /usr/src/app/node_modules
      - ../libs:/usr/src/libs
    networks:
      - service-network
    depends_on:
      - rabbitmq
      - logging-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  logging-service:
    build:
      context: ../
      dockerfile: apps/logging-service/dockerfile
    container_name: logging-service
    env_file:
      - ../apps/logging-service/.env.dev
    environment:
      - RUN_MODE=${RUN_MODE:-dev}

    ports:
      - "5002:5002"
      - "9231:9231"
    volumes:
      - ../apps/logging-service:/usr/src/app
      - /usr/src/app/node_modules
      - ../libs:/usr/src/libs
    networks:
      - service-network
    depends_on:
      - rabbitmq

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5002/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  user-service:
    build:
      context: ../
      dockerfile: apps/user-service/dockerfile
    container_name: user-service
    env_file:
      - ../apps/user-service/.env.dev
    environment:
      - RUN_MODE=${RUN_MODE:-dev}

    ports:
      - "5003:5003"
      - "9232:9232"
    volumes:
      - ../apps/user-service:/usr/src/app
      - /usr/src/app/node_modules
      - ../libs:/usr/src/libs
    networks:
      - service-network
    depends_on:
      - rabbitmq

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5003/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5674:5672"
      - "15690:15672"
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  service-network:
    driver: bridge
