# Use an official Node.js runtime as a parent image
FROM node:22-alpine AS base

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY apps/user-service/package*.json ./


# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY apps/user-service ./
COPY libs ./libs


# Expose the port the app runs on
EXPOSE 5003


# Define the command to run the app
CMD ["sh", "-c", "npm run start:${RUN_MODE}"]