// const DeviceSchema = new mongoose.Schema({
//     // Unique device identifier (generated by combining multiple factors)
//     deviceId: {
//       type: String,
//       required: true,
//       unique: true,
//       index: true
//     },

//     // User who owns this device
//     user: {
//       type: mongoose.Schema.Types.ObjectId,
//       ref: 'User',
//       required: true,
//       index: true
//     },

//     // Device Information
//     deviceInfo: {
//       // Browser/App Information
//       userAgent: {
//         type: String,
//         required: true
//       },

//       // Parsed User Agent Details
//       browser: {
//         name: String,
//         version: String,
//         major: String
//       },

//       engine: {
//         name: String,
//         version: String
//       },

//       os: {
//         name: String,
//         version: String
//       },

//       device: {
//         vendor: String,
//         model: String,
//         type: String // mobile, tablet, desktop
//       },

//       // Screen/Display Information
//       screen: {
//         width: Number,
//         height: Number,
//         pixelRatio: Number
//       },

//       // Browser capabilities
//       capabilities: {
//         cookieEnabled: Boolean,
//         javaEnabled: Boolean,
//         language: String,
//         languages: [String],
//         platform: String,
//         timezone: String,
//         touchSupport: Boolean
//       }
//     },

//     // Network Information
//     networkInfo: {
//       // IP Address (store hashed for privacy)
//       ipHash: String,
//       // Store actual IP only if needed for security (encrypted)
//       ipAddress: String, // Consider encrypting this

//       // Geographic location (approximate)
//       location: {
//         country: String,
//         countryCode: String,
//         region: String,
//         city: String,
//         latitude: Number,
//         longitude: Number,
//         timezone: String,
//         isp: String
//       },

//       // Connection details
//       connectionType: String, // wifi, cellular, ethernet
//       downlink: Number, // Network speed
//       effectiveType: String // slow-2g, 2g, 3g, 4g
//     },

//     // Device Fingerprinting (for advanced security)
//     fingerprint: {
//       // Canvas fingerprint (helps detect same device)
//       canvasFingerprint: String,

//       // WebGL fingerprint
//       webglFingerprint: String,

//       // Audio fingerprint
//       audioFingerprint: String,

//       // Font fingerprint
//       fontFingerprint: String,

//       // Combined unique fingerprint hash
//       combinedHash: String
//     },

//     // Device Status
//     status: {
//       type: String,
//       enum: ['active', 'inactive', 'blocked', 'suspicious'],
//       default: 'active'
//     },

//     // Trust Level (calculated based on usage patterns)
//     trustLevel: {
//       type: String,
//       enum: ['low', 'medium', 'high', 'verified'],
//       default: 'low'
//     },

//     // Security Information
//     security: {
//       // Risk score (0-100, higher = more risky)
//       riskScore: {
//         type: Number,
//         default: 0,
//         min: 0,
//         max: 100
//       },

//       // Flags for suspicious activity
//       flags: [{
//         type: {
//           type: String,
//           enum: ['new_location', 'unusual_activity', 'bot_like', 'proxy_detected', 'vpn_detected']
//         },
//         severity: {
//           type: String,
//           enum: ['low', 'medium', 'high', 'critical']
//         },
//         description: String,
//         detectedAt: Date,
//         resolved: {
//           type: Boolean,
//           default: false
//         }
//       }],

//       // Two-factor authentication status for this device
//       twoFactorEnabled: {
//         type: Boolean,
//         default: false
//       },

//       // Device verification status
//       isVerified: {
//         type: Boolean,
//         default: false
//       },

//       // Last security check
//       lastSecurityCheck: Date
//     },

//     // Usage Statistics
//     usage: {
//       // First time this device was seen
//       firstSeen: {
//         type: Date,
//         default: Date.now
//       },

//       // Last activity timestamp
//       lastSeen: {
//         type: Date,
//         default: Date.now
//       },

//       // Total login count from this device
//       loginCount: {
//         type: Number,
//         default: 1
//       },

//       // Failed login attempts
//       failedAttempts: {
//         type: Number,
//         default: 0
//       },

//       // Last failed attempt timestamp
//       lastFailedAttempt: Date,

//       // Session duration statistics
//       averageSessionDuration: Number,
//       totalSessionTime: Number,

//       // Activity patterns
//       activeHours: [Number], // Hours of day when device is active (0-23)
//       activeDays: [Number],  // Days of week when device is active (0-6)

//       // Location history (last 10 locations)
//       locationHistory: [{
//         country: String,
//         city: String,
//         timestamp: Date,
//         ipHash: String
//       }]
//     },

//     // Device Name (user-friendly name set by user)
//     name: {
//       type: String,
//       default: function() {
//         // Auto-generate friendly name
//         const os = this.deviceInfo?.os?.name || 'Unknown';
//         const browser = this.deviceInfo?.browser?.name || 'Browser';
//         return `${os} - ${browser}`;
//       }
//     },

//     // User can set custom name
//     customName: String,

//     // Device registration/linking
//     isRegistered: {
//       type: Boolean,
//       default: false
//     },

//     // Push notification token (for mobile devices)
//     pushToken: String,

//     // App version (for mobile apps)
//     appVersion: String,

//     // Device settings
//     settings: {
//       // Remember this device
//       rememberDevice: {
//         type: Boolean,
//         default: false
//       },

//       // Notification preferences for this device
//       notifications: {
//         securityAlerts: {
//           type: Boolean,
//           default: true
//         },
//         loginAlerts: {
//           type: Boolean,
//           default: true
//         }
//       }
//     }
//   }, {
//     timestamps: true,
//     // Add indexes for common queries
//     toJSON: { virtuals: true },
//     toObject: { virtuals: true }
//   });

//   // ================================
//   // INDEXES FOR PERFORMANCE
//   // ================================

//   DeviceSchema.index({ user: 1, status: 1 });
//   DeviceSchema.index({ deviceId: 1 }, { unique: true });
//   DeviceSchema.index({ 'usage.lastSeen': 1 });
//   DeviceSchema.index({ 'security.riskScore': 1 });
//   DeviceSchema.index({ trustLevel: 1 });
//   DeviceSchema.index({ 'networkInfo.ipHash': 1 });

//   // TTL index to auto-delete inactive devices after 1 year
//   DeviceSchema.index(
//     { 'usage.lastSeen': 1 },
//     {
//       expireAfterSeconds: 365 * 24 * 60 * 60,
//       partialFilterExpression: { status: 'inactive' }
//     }
//   );

//   // ================================
//   // VIRTUAL FIELDS
//   // ================================

//   DeviceSchema.virtual('displayName').get(function() {
//     return this.customName || this.name;
//   });

//   DeviceSchema.virtual('isOnline').get(function() {
//     // Consider device online if last seen within 5 minutes
//     const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);
//     return this.usage.lastSeen > fiveMinutesAgo;
//   });

//   DeviceSchema.virtual('daysSinceFirstSeen').get(function() {
//     const diffTime = Math.abs(new Date() - this.usage.firstSeen);
//     return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
//   });
