# Use an official Node.js runtime as a parent image
FROM node:22-alpine AS stage

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY apps/logging-service/package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY apps/api-gateway ./
COPY libs ./libs

# Expose the port the app runs on
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:3000/health || exit 1

# Define the command to run the app

CMD ["npm", "run", "dev"]